import React, { useState, useEffect } from 'react';
import { RefreshCcw, HelpCircle } from 'lucide-react';
import { GeneratedContent } from '../services/api';
import './app.css';

interface CreativeSparkPanelProps {
  content: GeneratedContent;
  addOnUISdk: any;
  onToast: (message: string, type?: 'success' | 'error' | 'info') => void;
}

const CreativeSparkPanel: React.FC<CreativeSparkPanelProps> = ({ content, onToast }) => {
  const [activeTab, setActiveTab] = useState('ideas');
  const [keywordInput, setKeywordInput] = useState('');
  const [brainstormInput, setBrainstormInput] = useState('');
  const [selectedLanguage, setSelectedLanguage] = useState('English');
  const [designScore, setDesignScore] = useState(70);
  const [accordionOpen, setAccordionOpen] = useState<string[]>(['score', 'quickFixes']);
  const [showTutorial, setShowTutorial] = useState(false);
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    let score = 100;
    if (content.caption.length > 150) score -= 20;
    if (content.hashtags.length < 5) score -= 10;
    if (content.colorPalette.every(c => c === content.colorPalette[0])) score -= 15;
    if (content.layoutTips.length < 3) score -= 5;
    if (content.accessibilitySuggestions.some(s => s.issue.includes('contrast'))) score -= 10;
    setDesignScore(Math.max(0, Math.min(100, score)));

    if (!content.trends.some(t => t.description.includes('Trending'))) {
      onToast('Trends generated by Groq AI.', 'info');
    }
    if (!content.multilingualContent.some(l => l.language !== 'English' && l.caption !== content.caption)) {
      onToast('Google Translate API key missing. Using default captions.', 'info');
    }
    if (!content.moodBoard.some(m => m.imageUrl && !m.imageUrl.includes('placeholder'))) {
      onToast('Unsplash API key missing. Using placeholder images.', 'info');
    }
  }, [content]);

  const toggleAccordion = (section: string) => {
    setAccordionOpen(prev => 
      prev.includes(section) ? prev.filter(s => s !== section) : [...prev, section]
    );
  };

  const copyText = (text: string, type: string) => {
    try {
      // Use prompt as fallback for clipboard access
      window.prompt(`Copy ${type} to clipboard:`, text);
      onToast(`${type} ready to copy!`, 'success');
    } catch (error) {
      onToast(`Failed to prepare ${type} for copying.`, 'error');
      console.error('Copy error:', error);
    }
  };

  const generateBrainstormIdeas = async () => {
    if (!brainstormInput) {
      onToast('Please enter a brainstorm prompt.', 'error');
      return;
    }
    setIsLoading(true);
    try {
      onToast('Brainstorm ideas generated!', 'success');
    } catch (error) {
      onToast('Failed to generate brainstorm ideas.', 'error');
      console.error('Brainstorm error:', error);
    } finally {
      setIsLoading(false);
    }
  };

  const updateKeywords = async () => {
    if (!keywordInput) {
      onToast('Please enter a keyword prompt.', 'error');
      return;
    }
    setIsLoading(true);
    try {
      onToast('Keywords updated!', 'success');
    } catch (error) {
      onToast('Failed to update keywords.', 'error');
      console.error('Keyword update error:', error);
    } finally {
      setIsLoading(false);
    }
  };

  const renderScoreGauge = () => (
    <div className="score-gauge">
      <svg viewBox="0 0 100 100">
        <circle cx="50" cy="50" r="45" fill="none" stroke="#d1d5db" strokeWidth="10" />
        <circle
          cx="50"
          cy="50"
          r="45"
          fill="none"
          stroke={designScore > 75 ? '#22c55e' : designScore > 50 ? '#f59e0b' : '#ef4444'}
          strokeWidth="10"
          strokeDasharray={`${designScore * 2.83}, 283`}
          transform="rotate(-90 50 50)"
        />
        <text x="50" y="55" textAnchor="middle" className="score-text">{designScore}</text>
      </svg>
      <p style={{ fontSize: '11px', textAlign: 'center', color: '#1e40af' }}>
        {designScore > 75 ? 'Great: Ready to shine!' : designScore > 50 ? 'Good: Needs minor tweaks' : 'Needs work: Check quick fixes'}
      </p>
    </div>
  );

  const renderTutorialModal = () => (
    <div className="tutorial-modal">
      <div className="tutorial-content">
        <h2>CreativeSpark AI Tutorial</h2>
        <p style={{ fontSize: '11px', color: '#6b7280' }}>Get started with your design assistant!</p>
        <ol>
          <li><strong>Configure Settings:</strong> Enter your Groq API key and optional API keys.</li>
          <li><strong>Generate Content:</strong> Use the prompt to get ideas, SEO keywords, and more.</li>
          <li><strong>Copy Suggestions:</strong> Copy captions, hashtags, or keywords to your design.</li>
          <li><strong>SEO & Trends:</strong> Optimize with AI-generated keywords and trends.</li>
          <li><strong>Export:</strong> Use Adobe Express to export your final design.</li>
        </ol>
        <button onClick={() => setShowTutorial(false)}>Close Tutorial</button>
      </div>
    </div>
  );

  return (
    <div className="creativespark-panel">
      <div className="tab-group">
        {['ideas', 'brainstorm', 'keywords', 'recommendations', 'moodBoard', 'trends'].map(tab => (
          <div
            key={tab}
            className={`tab ${activeTab === tab ? 'active' : ''}`}
            onClick={() => setActiveTab(tab)}
          >
            {tab.charAt(0).toUpperCase() + tab.slice(1).replace('Board', ' Board')}
          </div>
        ))}
      </div>

      {activeTab === 'ideas' && (
        <div>
          <div className="recommendation-card">
            <strong>Fresh Ideas</strong>
            <p style={{ fontSize: '11px', color: '#6b7280' }}>
              Use these suggestions to kickstart your design.
            </p>
            {content.freshIdeas.map((idea, i) => (
              <div key={i} style={{ margin: '6px 0' }}>
                <strong>{idea.description}</strong>: {idea.content || 'Add to canvas'}
                <button className="action-button" onClick={() => copyText(idea.content || idea.description, 'Idea')}>
                  Copy
                </button>
              </div>
            ))}
          </div>
        </div>
      )}

      {activeTab === 'brainstorm' && (
        <div>
          <div className="recommendation-card">
            <strong>Brainstorm Prompt:</strong>
            <input
              className="input"
              value={brainstormInput}
              onChange={e => setBrainstormInput(e.target.value)}
              placeholder="Enter a theme (e.g., summer sale, tech product)"
            />
            <button
              className="action-button"
              onClick={generateBrainstormIdeas}
              disabled={isLoading}
            >
              {isLoading ? <span className="loading-spinner" /> : <RefreshCcw size={12} />} Generate Ideas
            </button>
          </div>
          {content.brainstormIdeas?.map((idea, i) => (
            <div key={i} className="recommendation-card">
              <strong>{idea.idea}</strong>: {idea.description}
              <button className="action-button" onClick={() => copyText(idea.description, 'Idea')}>
                Copy
              </button>
            </div>
          ))}
        </div>
      )}

      {activeTab === 'keywords' && (
        <div>
          <div className="recommendation-card">
            <strong>Keyword Input:</strong>
            <input
              className="input"
              value={keywordInput}
              onChange={e => setKeywordInput(e.target.value)}
              placeholder="Enter product or theme..."
            />
            <button
              className="action-button"
              onClick={updateKeywords}
              disabled={isLoading}
            >
              {isLoading ? <span className="loading-spinner" /> : <RefreshCcw size={12} />} Update Keywords
            </button>
          </div>
          {content.keywordSuggestions.map((keyword, i) => (
            <div key={i} className="recommendation-card">
              <strong>{keyword.keyword} ({keyword.relevance}%)</strong>: {keyword.suggestion}
              <button className="action-button" onClick={() => copyText(keyword.keyword, 'Keyword')}>
                Copy
              </button>
            </div>
          ))}
        </div>
      )}

      {activeTab === 'recommendations' && (
        <div>
          <div className="preview-canvas">
            <div
              className="preview-text"
              style={{ background: content.colorPalette[0], color: content.colorPalette[1] }}
            >
              {content.caption.substring(0, 50)}...
            </div>
          </div>
          <div className="accordion">
            <div className="accordion-header" onClick={() => toggleAccordion('score')}>
              Design Health Score
              <span>{accordionOpen.includes('score') ? '−' : '+'}</span>
            </div>
            {accordionOpen.includes('score') && (
              <div className="accordion-content active">
                {renderScoreGauge()}
                <div className="recommendation-card">
                  <strong>Breakdown:</strong>
                  <ul style={{ fontSize: '11px', paddingLeft: '12px' }}>
                    <li>Caption: {content.caption.length > 150 ? 'Too long' : 'Good length'}</li>
                    <li>Hashtags: {content.hashtags.length >= 5 ? 'Sufficient' : 'Add more'}</li>
                    <li>Colors: {content.colorPalette.every(c => c === content.colorPalette[0]) ? 'Low variety' : 'Good variety'}</li>
                    <li>Accessibility: {content.accessibilitySuggestions.length > 0 ? 'Issues detected' : 'Compliant'}</li>
                  </ul>
                </div>
              </div>
            )}
          </div>
          <div className="accordion">
            <div className="accordion-header" onClick={() => toggleAccordion('quickFixes')}>
              Quick Fixes
              <span>{accordionOpen.includes('quickFixes') ? '−' : '+'}</span>
            </div>
            {accordionOpen.includes('quickFixes') && (
              <div className="accordion-content active">
                {content.quickFixes.map((fix, i) => (
                  <div key={i} className="recommendation-card">
                    <strong>{fix.issue}</strong>: {fix.suggestion}
                    {fix.action === 'applyColor' && (
                      <button className="action-button" onClick={() => copyText(content.colorPalette[1], 'Color')}>
                        Copy Color
                      </button>
                    )}
                  </div>
                ))}
              </div>
            )}
          </div>
          <div className="accordion">
            <div className="accordion-header" onClick={() => toggleAccordion('content')}>
              Content Suggestions
              <span>{accordionOpen.includes('content') ? '−' : '+'}</span>
            </div>
            {accordionOpen.includes('content') && (
              <div className="accordion-content active">
                <div className="recommendation-card">
                  <strong>Multilingual Copy:</strong>
                  <select
                    className="dropdown"
                    value={selectedLanguage}
                    onChange={e => setSelectedLanguage(e.target.value)}
                  >
                    {content.multilingualContent.map(lang => (
                      <option key={lang.language} value={lang.language}>{lang.language}</option>
                    ))}
                  </select>
                </div>
                <div className="recommendation-card">
                  <strong>Caption:</strong> {content.multilingualContent.find(l => l.language === selectedLanguage)?.caption || content.caption}
                  <button className="action-button" onClick={() => copyText(content.multilingualContent.find(l => l.language === selectedLanguage)?.caption || content.caption, 'Caption')}>
                    Copy
                  </button>
                </div>
                <div className="recommendation-card">
                  <strong>CTA:</strong> {content.multilingualContent.find(l => l.language === selectedLanguage)?.cta || content.cta}
                  <button className="action-button" onClick={() => copyText(content.multilingualContent.find(l => l.language === selectedLanguage)?.cta || content.cta, 'CTA')}>
                    Copy
                  </button>
                </div>
                <div className="recommendation-card">
                  <strong>Hashtags:</strong> {content.hashtags.join(' ')}
                  <button className="action-button" onClick={() => copyText(content.hashtags.join(' '), 'Hashtags')}>
                    Copy
                  </button>
                </div>
              </div>
            )}
          </div>
          <div className="accordion">
            <div className="accordion-header" onClick={() => toggleAccordion('design')}>
              Design Suggestions
              <span>{accordionOpen.includes('design') ? '−' : '+'}</span>
            </div>
            {accordionOpen.includes('design') && (
              <div className="accordion-content active">
                <div className="recommendation-card">
                  <strong>Fonts:</strong> {content.fonts.join(', ')}
                </div>
                <div className="recommendation-card">
                  <strong>Color Palette:</strong>
                  <div style={{ display: 'flex', gap: '6px', marginTop: '4px', flexWrap: 'wrap' }}>
                    {content.colorPalette.map((color, i) => (
                      <div
                        key={i}
                        className="tooltip"
                        style={{ width: '18px', height: '18px', backgroundColor: color, borderRadius: '4px', border: '1px solid #d1d5db', cursor: 'pointer' }}
                        onClick={() => copyText(color, 'Color')}
                      >
                        <span className="tooltip-text">{color}</span>
                      </div>
                    ))}
                  </div>
                </div>
                <div className="recommendation-card">
                  <strong>Layout Tips:</strong>
                  <ul style={{ fontSize: '11px', paddingLeft: '12px' }}>
                    {content.layoutTips.map((tip, i) => (
                      <li key={i}>{tip}</li>
                    ))}
                  </ul>
                </div>
              </div>
            )}
          </div>
          <div className="accordion">
            <div className="accordion-header" onClick={() => toggleAccordion('accessibility')}>
              Accessibility Suggestions
              <span>{accordionOpen.includes('accessibility') ? '−' : '+'}</span>
            </div>
            {accordionOpen.includes('accessibility') && (
              <div className="accordion-content active">
                {content.accessibilitySuggestions.map((suggestion, i) => (
                  <div key={i} className="recommendation-card">
                    <strong>{suggestion.issue}</strong>: {suggestion.suggestion}
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      )}

      {activeTab === 'moodBoard' && (
        <div>
          <div className="mood-board">
            {content.moodBoard.map((item, i) => (
              <div
                key={i}
                className="mood-item"
                style={{ background: item.color || '#f3f4f6' }}
              >
                {item.imageUrl ? (
                  <img src={item.imageUrl} alt={item.description} style={{ maxWidth: '100px', borderRadius: '4px' }} />
                ) : (
                  <span>{item.description}</span>
                )}
              </div>
            ))}
          </div>
          <p style={{ fontSize: '11px', color: '#6b7280', textAlign: 'center' }}>
            Add these images to your Adobe Express library.
          </p>
        </div>
      )}

      {activeTab === 'trends' && (
        <div>
          {content.trends.map((trend, i) => (
            <div key={i} className="recommendation-card">
              <strong>{trend.hashtag}</strong>: {trend.description} (Popularity: {trend.popularity}%)
              <button className="action-button" onClick={() => copyText(trend.hashtag, 'Hashtag')}>
                Copy
              </button>
            </div>
          ))}
        </div>
      )}

      <button className="help-button" onClick={() => setShowTutorial(true)} title="View Tutorial">
        <HelpCircle size={20} />
      </button>
      {showTutorial && renderTutorialModal()}
    </div>
  );
};

export default CreativeSparkPanel;